spring:
  datasource:
    username: tj
    password: 123456
    url: jdbc:mysql://localhost:3306/ms?useUnicode=true&characterEncoding=utf8
logging:
  level:
    root: INFO   
    com.example: debug



    